config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create], path_names: { new: 'signup' }

  resources :sessions, only: [:new, :create], path_names: { new: 'login'} do
    collection do
      delete 'logout' => 'sessions#destroy'
    end
  end

  resources :categories do
    resources :tasks do
      collection do
        get 'today' => 'tasks#due_today', as: :due_today
      end
    end
  end

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, foreign_key: :username, primary_key: :username
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  has_one :user, through: :category
  validates :title, :description, :due_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, foreign_key: :username, primary_key: :username
  has_many :tasks, through: :categories
  has_secure_password
  

  validates :email, :username, presence: true
  validates_uniqueness_of :email, :username
  validates :password, presence: true, length: { in: 6..15 }, format: { with: /\A(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[^a-zA-Z0-9]).{6,15}\z/, message: "must include at least one letter, one number, and one symbol" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find_by("username = ? OR email = ?", session[:user_username], session[:user_email])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params.merge(username: current_user.username))
  
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def show
    @category = current_user.categories.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @category }
    end
  end

  def edit
    @category = current_user.categories.find(params[:id])
  end

  def update
    @category = current_user.categories.find(params[:id])
      if @category.update(category_params)
        redirect_to @category, notice: 'Category was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy

      respond_to do |format|
        format.html { redirect_to categories_path, notice: 'Category was successfully deleted.' }
        format.json { head :no_content }
      end
  end
  
  private
    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = current_user.categories.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create    
    username_or_email = session_params[:username_or_email]
    user = User.find_by(username: username_or_email) || User.find_by(email: username_or_email)

    if user && user.authenticate(session_params[:password])
      session[:user_username] = user.username
      session[:user_email] = user.email
      redirect_to categories_path(current_user)
      flash[:notice] = 'Login successful.'
    else
      flash.now[:alert] = 'Invalid login details. Please try again.'
      render 'new'
    end
  end

  def destroy
    session[:user_username] = nil
    session[:user_email] = nil
    redirect_to root_path
    flash[:notice] = 'You have been logged out. Login again.'
  end
end

private
def session_params
  params.permit(:username_or_email, :password, :authenticity_token, :commit)
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category, only: [:index, :new, :create, :show, :due_today, :edit, :update, :destroy]

  def index
    @tasks = @category.tasks
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to category_path(@category), notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @task = current_user.tasks.find(params[:id])
    @category = @task.category
  end

  def edit
    @task = current_user.tasks.find(params[:id])
    @category = @task.category
  end

  def update
    @task = current_user.tasks.find(params[:id])
    @category = @task.category
  
    if @task.update(task_params)
      redirect_to category_path(@category), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end
  

  def destroy
    @task = current_user.tasks.find(params[:id])
    @category = @task.category
    @task.destroy
    redirect_to category_path(@category), notice: 'Task was successfully deleted.'
  end

  def due_today
    @tasks = @category.tasks.where(due_date: Date.today).order(:due_date)
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :due_date)
  end

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to categories2_path,    
      flash[:notice] = 'Registration successful!'
    else
      render :new
      flash[:notice] = 'Registration failed! Please try again.'

    end
  end

  def save_note
    note_content = params[:note_content]
    current_user.update(note_content: note_content)
    flash[:notice] = "Note content saved."
    render json: { content: note_content }
  end
  

  private
    def user_params
      params.require(:user).permit(
        :first_name,
        :middle_name,
        :last_name,
        :date_of_birth,
        :email,
        :username,
        :password,
        :password_confirmation,
        :note_content
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: @category, url: @category.persisted? ? category_path(@category) : categories_path, local: true, data: { turbo: false }) do |form| %>
    
  <% if @category.errors.any? %>
    <div class="error_explanation">
      <% @category.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>

  <div class="new_category_container">
    <div>
      <strong><%= form.label :name %></strong>
      <%= form.text_field :name, :id => 'category_input' %>
    </div>

      <%= form.submit :id => "category_button" %>
  </div>

<% end %>

app/views/categories/edit.html.erb
<div class="edit_category_container">
  <h3>Edit Category</h3>

  <%= render 'form' %>

  <div class="back_link_container">
    <%= link_to 'Back', categories_path, :class => "back_to_categories" %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="hi_user">
  <h3>Hello, <%= current_user.first_name %>!</h3>
  <%= button_to "Logout", logout_sessions_path, method: :delete, :class => 'logout' %>
  </div>

<div class="categories_notepad_container">
  <div class="categories_container"> 
    <h3>Categories</h3>

    <% if @categories.empty? %>
      <p class="opening_message">To start, create a New Category.</p>
    <% end %>

    <div class="categories_list">
      <% @categories.each do |category| %>
        <li class="tasks_list">
          <%= link_to category.name, category_path(category), :id => "category_name" %>
          <div class="category_actions">
              <%= link_to 'Tasks Due Today', due_today_category_tasks_path(category), :id=>"due_tasks" %> |
              <%= link_to 'Edit', edit_category_path(category), :id =>"edit_category" %> |
              <%= button_to 'Delete', category_path(category), method: :delete, :id=>"delete_category" %>
            </div>
        </li>
      <% end %>
    </div>

    <div>
      <%= link_to 'New Category', new_category_path, :id=>"new_category" %>
    </div>
  </div>

<div class="notepad_container">
  <h3>Your Notepad</h3>
  <form data-turbo-frame="notepad">
    <p id="notepad_text">Type your thoughts here...</p>
    <textarea id="notepad"><%= current_user.note_content %></textarea>
    <button id="saveNote">
      <%= current_user.note_content.present? ? 'Update' : 'Save' %>
    </button>
  </form>
</div>


</div>

app/views/categories/new.html.erb
<div class="new_category_container">
  <h3>New Category</h3>

  <%= render 'form' %>

  <div id="back_to_category">
    <%= link_to 'Back', @category.persisted? ? category_path(@category) : categories_path %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="tasks_in_categories">
  <h3><%= @category.name %></h3>

  
    <div class="task_list">
      <% if @category.tasks.empty? %>
        <p class="opening_message">Create your first task.</p>
      <% end %>
    
      <% @category.tasks.each do |task| %>
      <div class="each_task_container">
        <p id="title">Title:</p>
        <p id="title_content"><%= task.title %></p>
        <p id="description">Description:</p>
        <p id="description_content"><%= task.description %></p>
        <p id="due_date">Due Date:</p>
        <p id="date_of_due"><%= task.due_date.strftime("%B %d, %Y (%A)") %></p>
    
        <div class="tasks_buttons_container">
          <%= button_to 'Edit', edit_category_task_path(@category, task), :id => "edit_task" %>|
          <%= button_to 'Delete', category_task_path(@category, task), :method => :delete, :id => "delete_task" %>
        </div>
      </div>
    <% end %>

      <div class="buttons_container">
        <%= link_to 'New Task', new_category_task_path(@category), :id => "new_task" %>
        <%= link_to 'Back', categories_path, :class => "back_to_categories" %>
      </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p class="footer">&copy; 2023 TasksMaster. All rights reserved.
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1>TasksMaster</h1>
  <a href="/">
    <img src="/TasksMaster.png" alt="TasksMaster Logo">
  </a>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksMaster</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    </head>

  <body>

  <div class="main-content">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>
  
    <%= render 'layouts/header' %>

    <%= yield %>
  </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="login_video_containers">    
    <div class="site_info_container">
      <p>Welcome to TasksMaster, your personal productivity companion designed to simplify your daily tasks and boost your efficiency. </p>
      <p> TasksMaster is not just a to-do list app; it's your ultimate task management solution. </p>

      <p class="home_options">Let's get started!</p>
        <a href="<%= new_session_path %>" class="login_link">Login</a>
        <a href="<%= new_user_path %>" class="register_link">Register</a>
    </div>

    <div class="video_container">
      <video autoplay muted loop>
        <source src="/TaskMasterVideo.mp4" type="video/mp4">
        Your browser does not support the video tag.
      </video>
    </div>
  </div>

app/views/tasks/_form.html.erb
<%# <%= form_with(model: [@category, @task], local: true, url: @task.persisted? ? category_task_path(@category, @task) : category_tasks_path(@category), action: @task.persisted? ? category_tasks_path(@category) : category_tasks_path(@category), data: {turbo: false}) do |form| %> 

<%= form_with(model: [@category, @task], local: true) do |form| %>
  <div class="task_inputs_container">
    <div class="title_field">
      <strong><%= form.label :title %></strong>
      <%= form.text_field :title %>
    </div>

    <div class="description_field">
      <strong><%= form.label :description %></strong>
      <%= form.text_area :description %>
    </div>

    <div class="due_date_field">
      <strong><%= form.label :due_date %></strong>
      <%= form.date_field :due_date %>
    </div>

    <div class="submit_button">
      <%= form.submit %>
    </div>

    <div id="error_explanation">
      <% if @task.errors.any? %>
        <% @task.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

<% if @task.persisted? %>
  <div class="delete_task_container">
    <%= button_to 'Delete', category_task_path(@category, @task), :method => :delete, :class => "delete_task" %>
  </div>
<% end %>

app/views/tasks/due_today.html.erb
  <div class="due_tasks_container">
  <h3 id="due_today_text">Tasks Due Today</h3>

    <% if @tasks.present? %>
      <% @tasks.each do |task| %>
        <li>
        <%= link_to "#{task.title}", category_task_path(task.category, task) %>
        </li>
      <% end %>
    <% else %>
      <p>You currently have no pending tasks.</p>
    <% end %>

  <div>
    <%= link_to 'Back', categories_path, :id => "back_to_category" %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task %>

<div class="back_link_container">
  <%= link_to 'Back', category_path(@category), :class=>"back_to_category" %>
</div>

app/views/tasks/new.html.erb
<div class="new_task_container">
  <h3>New Task</h3>

  <%= render 'form', task: @task %>

  <div>
    <%= link_to 'Back', category_path(@category), :id=>"back_to_category" %>
  </div>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<div class="task_show_details">
  <p><strong>Description:</strong> <%= @task.description %></p>
  <p><strong>Due Date:</strong> <%= @task.due_date %></p>
</div>

<div class="buttons_containers">
  <%= link_to 'Edit', edit_category_task_path(@category, @task), :class => "edit_task" %>
  <%= button_to 'Delete', category_task_path(@category, @task), :method => :delete, :data => { :confirm => 'Confirm Delete?' }, :class => "delete_task" %>
  <%= link_to 'Back', category_path(@category), :class => "back_to_category" %>
</div>

app/views/users/new.html.erb
<div class="registration_container">
  <h3>Register with TasksMaster!</h3>

    <div class="registration_form_container">
      <%= form_with(model: @user, url: users_path, local: true) do |form| %>
        <%= form.label :first_name %>
        <%= form.text_field :first_name, required: true, :class => "registration_input" %>

        <%= form.label :middle_name %>
        <%= form.text_field :middle_name, :class => "registration_input" %>

        <%= form.label :last_name %>
        <%= form.text_field :last_name, required: true, :class => "registration_input" %>
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth, required: true, :class => "registration_input" %>

        <%= form.label :email %>
        <%= form.email_field :email, required: true, :class => "registration_input" %>

        <%= form.label :username %>
        <%= form.text_field :username, required: true, :class => "registration_input" %>

        <%= form.label :password %>
        <%= form.password_field :password, required: true, :class => "registration_input" %>

        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, required: true, :class => "registration_input" %>

        <%= form.submit 'Register', :id => "register_button" %>
      <% end %>
    </div>

    <div class="login">
      <%= link_to 'Already have an account?', new_session_path %>
    </div>
</div>